### ISSUE TITLE
Error with TerraformFmt and terraform 0.12

### ISSUE THREAD

**Issue by commarla** [hashivim/vim-terraform#107]
Hi,

Since my upgrade to tf 0.12, the TerraformFmt command doesn't work anymore :
```
[[31m
^[[1m^[[31mError: ^[[0m^[[0m^[[1mNo file or directory at ../../../../../var/folders/cc/y5w0cx2510xb7lwvlvqg0gkw0000gn/T/v7ive4X/11.tf^[[0m

^[[0m^[[0m^[[0m

```

I don't know anything about vim plugin so any help would be appreciated.

Thanks,

**Comment by dimbleby** [comment]
I don't think you can be running a recent version of the plugin.  Please check, upgrade, try again.

**Comment by commarla** [comment]
Thanks @dimbleby I was using https://github.com/hashivim/vim-hashicorp-tools which seems to be up to date. 
Deleting it and cloning vim-terraform solved the issue.
