### ISSUE TITLE
added as maintainer

### ISSUE THREAD

**Issue by tkjef** [hashivim/vim-terraform#110]
hello,

i would like to be added as a maintainer.

vim and terraform are probably my 2 favorite technologies. i've been using Vim for 12 years and Terraform for 2 years extensively. 

nerdcommenter & vim-gitgutter are awesome vim plugins i like to use. oh, yeah, and vim-terraform!

i made a small vim plugin here: https://github.com/tkjef/vim_github_urls

thanks,
tkjef

**Comment by dimbleby** [comment]
I don't have the power to do anything about this; but more maintainers sounds like a good thing.

Do you have changes in mind that you'd like to make?  Please feel free to send merge requests anyway!

**Comment by tkjef** [comment]
sounds good.
