### ISSUE TITLE
Escaped slashes at end of string ignores closing quote

### ISSUE THREAD

**Issue by walterl** [hashivim/vim-terraform#112]
The escaped slash at the end of the string `"\"\\"` causes the closing double quote to be ignored.

The following declaration of the `skip` in `terraValueString` fixes that, and some related cases:

```vim
syn region terraValueString   start=/"/ skip=/\([^\\]\(\\\\\)*\)\@<=\\"/ end=/"/ contains=terraStringInterp`
```

**Comment by dimbleby** [comment]
Speaking for myself, this proposal is significantly more elaborate than I am comfortable with - I freely admit that I don't understand it!  (I wonder if the vim terraform syntax file is more complicated than it needs to be, and we aren't missing out on some simplification.)

I guess if we added enough testcases I could buy into it.  Eg I recently came across https://github.com/chrisbra/vim-xml-runtime, which has tests for syntax in https://github.com/chrisbra/vim-xml-runtime/tree/master/test/SYNTAX, so testing this stuff is possible.

However, I'm personally not motivated to get into this: to my mind it looks like a rather rare case that few people will hit.

So I guess I'm saying that, if it were only up to me, fixing this would require: a pull request, with some testcases demonstrating that this fixes something, and doesn't break related things.

(But it's not only up to me; I'm still new around here and if one of the established maintainers wants to go ahead with this, fair enough).
