### ISSUE TITLE
This seems to break vim-gitgutter.

### ISSUE THREAD

**Issue by ali-alsabbah** [hashivim/vim-terraform#117]
Nothing shows in the gutter with this plugin.

**Comment by dimbleby** [comment]
This sounds unlikely.

Please provide a minimal .vimrc to reproduce the problem, and a fuller description of what you're expecting vs what is happening.

(My guess is that in the process of minimizing the problem, you will discover that it lies elsewhere.)

**Comment by ali-alsabbah** [comment]
Huh, I tested out this out with a minimal vimrc, you were right. Then I switched back to my regular config and it worked.
