### ISSUE TITLE
[Feature Request] Execute terraform command in the context of folder of current file

### ISSUE THREAD

**Issue by drselump14** [hashivim/vim-terraform#121]
It would be nice if we can invoke the "Terraform" command in the context of the folder in the current file.

**Comment by dimbleby** [comment]
I don't think that this is something that this plugin should be doing.

Terraform projects aren't necessarily just a single file, but may be structured into modules in directories.  So just running from the directory of whichever file happens to be open is too naive.

I'd much prefer to keep this plugin simple and go with the usual Vim default of running commands from Vim's current working directory.

If you want to, you can set up your own configuration to change the current working directory as you prefer - eg `:help autochdir`, or by setting up an autocommand to do whatever it is you want.

**Comment by drselump14** [comment]
Oh, I didn't know about the autochdir options. Definetely will check that.  Thanks for the reply. I'll close this feature request
