### ISSUE TITLE
First class syntax support

### ISSUE THREAD

**Issue by nocode99** [hashivim/vim-terraform#122]
It seems this plugin has been updated for up to v0.12.x but I don't seem to see any support for syntax highlighting for first class expressions.

![vim-terraform-syntax](https://user-images.githubusercontent.com/4175239/68883393-eef8a380-06de-11ea-829a-8a807e59fce7.png)

I'm using nvim `0.3.8` with the latest version of the plugin. As you can see in the screenshot, it highlights some sections but when you look at `data.template_file.test.rendered`, it's only changing the syntax for `data` and `template_file` and not the full expression.

The recent changelog for terraform 0.12.14 indicates that first class expressions will eventually be enforced and I've held back on writing `"${var.test}"` as a first class expression simply for readability.

**Comment by dimbleby** [comment]
What would you like to see here?

Current highlighting looks fine to me: `data` and `template_file` are highlighted as keywords, other bits aren't.

A particularly good way of explaining what  you'd like to see would be a pull request demonstrating it, if you're up for that...

**Comment by dimbleby** [comment]
No response, treating as stale
