### ISSUE TITLE
Automate terraform update

### ISSUE THREAD

**Issue by kevinburkemeter** [hashivim/vim-terraform#125]
Hi,
Terraform v0.12.16 says the old string interpolation syntax is deprecated:

```
Warning: Interpolation-only expressions are deprecated

  on ../modules/test-notifier/test_notifier.tf line 27, in resource "aws_sns_topic_policy" "default":
  27:   arn    = "${aws_sns_topic.default.arn}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
```

Is there a way we can automate fixing these, in Vim? And/or update the syntax highlighting to match. This repo contains a tool that can be used to fix things: https://github.com/apparentlymart/terraform-clean-syntax

**Comment by dimbleby** [comment]
If you've already found a tool that makes the fixes that you want, suggest that you just use it!  Reinventing that wheel in Vimscript does not sound appealing...

Not sure what syntax highlighting change you're asking for.  Does your request duplicate #122?  As I said there, a particularly good way of explaining what you'd like to see would be a pull request demonstrating it, if you're up for that...

(But if this is a duplicate, let's close it.)

**Comment by dimbleby** [comment]
No response, treating as stale.
