### ISSUE TITLE
`terraform fmt` should not be executed on .tfvars

### ISSUE THREAD

**Issue by ikuwow** [hashivim/vim-terraform#129]
https://github.com/hashicorp/terraform/issues/15607#issuecomment-401985801

**Comment by dimbleby** [comment]
The issue you link to seems to say the opposite of what your issue title says - that other issue is complaining that `.tfvars` are ignored, whereas you are asking for that to happen.

Either way: `terraform fmt` currently _does_ format `.tfvars` files, and I don't see it as this plugin's place to overrule that.

If you don't want to format your `.tfvars` files then you can:

- (if you don't want to format-on-save then there's nothing to do, just don't format files that you don't want to format)
- disable `terraform_fmt_on_save`
- replace it with your own autocmd similar to [the one that this plugin uses](https://github.com/hashivim/vim-terraform/blob/bff65bf59401ef7d165637aedafe72f212ddf4c7/ftplugin/terraform.vim#L52-L58), but not including `*.tfvars`
