### ISSUE TITLE
Syntax highlighting for Terraform 0.7

### ISSUE THREAD

**Issue by drywheat** [hashivim/vim-terraform#14]
The changes to string interpolation in TF 0.7 have made it possible to nest and evaluate interpolations, but this plugin's syntax highlighting doesn't recognize this change. 

https://github.com/hashicorp/terraform/issues/6792, at the bottom of that timeline it is stated:

> ...when there is a string literal inside an interpolation (${ ... }) that string can itself contain interpolations. These nested interpolations can then contain their own strings, with their own interpolations again.

Here's a concrete example of what doesn't highlight well:

```hcl
resource "aws_subnet" "svc" {
    count = "${length(var.aws_zones)}"
    vpc_id = "${aws_vpc.main.id}"
    cidr_block = "${var.svc_subnets["zone${count.index}"]}"
    availability_zone = "${var.aws_zones["zone${count.index}"]}"

    tags {
        Name = "${var.region}-${var.env}-svc-${count.index}"
        Stack = "${var.stack}"
    }
}
```

**Comment by moritzheiber** [comment]
This is becoming more and more of an issue for use given the rising number of data sources and interpolation functions.

**Comment by pgporada** [comment]
@moritzheiber I'll be taking a look at this this coming weekend. Ping me again if I forget.

**Comment by moritzheiber** [comment]
@pgporada Reminding you, dutifully, to not forget about this issue :wink:

**Comment by pgporada** [comment]
@moritzheiber 

Can you send me a screenshot of what your vim looks like with the highlighting? Here's mine which seems messed up. To be completely honest, I've not used the Terraform coding style you're using with the zone array.

Can you show me the data structure of var.svc_subnets and what you expect `availability_zone = "${var.aws_zones["zone${count.index}"]}"` to output?

I have a suggestion for you as well
```
    count = "${length(var.aws_zones)}"

can be rewritten as

    count = "${length(compact(var.aws_zones))}"

which will produce count=0 if there are no aws_zones
```

:raised_hands:

**Comment by moritzheiber** [comment]
Here's the screenshot:

![screenshot_2017-02-27_22-02-21](https://cloud.githubusercontent.com/assets/616813/23379818/ad99e1e0-fd38-11e6-80fe-861100a0a47f.png)

**Comment by pgporada** [comment]
@moritzheiber Could I get examples of how your terraform code is structured? You're the first I've seen use the `cidr_block = "${var.svc_subnets["zone${count.index}"]}"` format. What I'm attempting to get at is, maybe a restructure of the data could be helpful.

What version of Terraform do you run now?

**Comment by drywheat** [comment]
Here's an example of where the syntax highlighting is defunct:

```hcl
resource "aws_subnet" "dmz" {
    count = "${length(var.aws_zones)}"
    vpc_id = "${aws_vpc.main.id}"
    cidr_block = "${var.dmz_subnets["${count.index}"]}"
    availability_zone = "${var.aws_zones["${count.index}"]}"
    map_public_ip_on_launch = true

    tags {
        Name = "${var.region}-${var.env}-sn-dmz-${count.index}"
        Stack = "${var.stack}"
        Environment = "${var.env}"
    }
}
```

The `cidr_block` and `availability_zone` assignments cause the issue. Lastly, here's a simple screenshot of how it looks in Vim ( notice how screwy it looks after `cidr_block` ):

![image](https://cloud.githubusercontent.com/assets/65274/23408009/728ca6c6-fd94-11e6-8c68-b5725d400855.png)

**Comment by pgporada** [comment]
Thanks for being patient everybody. Cheers to @ashb!

**Comment by drywheat** [comment]
🍾
