### ISSUE TITLE
Volunteering to help maintain HashiVim plugins

### ISSUE THREAD

**Issue by mattreduce** [hashivim/vim-terraform#144]
Hi @markcornick! Thanks for making the HashiVim set of plugins 😄 I saw your call for maintainers in the README and I'd love to help.

### Vim and Vimscript experience

* Have used Vim for more than 10 years
* Created and maintain the [`mix.vim`](https://github.com/mattreduce/vim-mix) plugin for Elixir

### HashiCorp tool experience

* An engineer at HashiCorp
* Familiar with and use every HashiCorp tool

Let me know if you have any questions 👍

**Comment by dimbleby** [comment]
I don't know if Mark is still around, I think @pgporada is the current holder of they keys.

Do you have changes in mind that you'd like to make? Please send merge requests anyway!

**Comment by pgporada** [comment]
Welcome aboard @mattreduce!
