### ISSUE TITLE
Terraform and TerraformFmt "Not an editor command"

### ISSUE THREAD

**Issue by Chris-Leeworthy** [hashivim/vim-terraform#145]
Hi, 

I'm new to using vim plugins but wanted to try this for my terraform work.

I am using Vim 8.1 on MacOS Catalina.

Used Git to install vim-terraform as per the instructions on the README.

When I go into a .tf file the syntax highlighting seems to be working but if I try to run the :Terraform or :TerraformFmt commands I get an error like the one below.
`E492: Not an editor command: Terraform`

I think syntax highlighting is working OK and I have checked the syntax settings.
`:setlocal syntax?`
 `syntax=terraform`

I have also run `:scriptnames` and confirmed that the plugin is loaded (see output below).  So now I'm stuck, I don't know what else to check or try.  
```
  1: /usr/share/vim/vimrc
  2: ~/.vimrc
  3: /usr/share/vim/vim81/syntax/syntax.vim
  4: /usr/share/vim/vim81/syntax/synload.vim
  5: /usr/share/vim/vim81/syntax/syncolor.vim
  6: /usr/share/vim/vim81/filetype.vim
  7: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
  8: /usr/share/vim/vim81/plugin/gzip.vim
  9: /usr/share/vim/vim81/plugin/logiPat.vim
 10: /usr/share/vim/vim81/plugin/manpager.vim
 11: /usr/share/vim/vim81/plugin/matchparen.vim
 12: /usr/share/vim/vim81/plugin/netrwPlugin.vim
 13: /usr/share/vim/vim81/plugin/rrhelper.vim
 14: /usr/share/vim/vim81/plugin/spellfile.vim
 15: /usr/share/vim/vim81/plugin/tarPlugin.vim
 16: /usr/share/vim/vim81/plugin/tohtml.vim
 17: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 18: /usr/share/vim/vim81/plugin/zipPlugin.vim
 19: ~/.vim/pack/plugins/start/lightline/plugin/lightline.vim
 20: ~/.vim/pack/plugins/start/vim-terraform/ftdetect/terraform.vim
 21: ~/.vim/pack/vendor/start/nerdtree/plugin/NERD_tree.vim
 22: ~/.vim/pack/vendor/start/nerdtree/autoload/nerdtree.vim
 23: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/path.vim
 24: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/menu_controller.vim
 25: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/menu_item.vim
 26: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/key_map.vim
 27: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/bookmark.vim
 28: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/tree_file_node.vim
 29: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/tree_dir_node.vim
 30: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/opener.vim
 31: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/creator.vim
 32: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/flag_set.vim
 33: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/nerdtree.vim
 34: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/ui.vim
 35: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/event.vim
 36: ~/.vim/pack/vendor/start/nerdtree/lib/nerdtree/notifier.vim
 37: ~/.vim/pack/vendor/start/nerdtree/autoload/nerdtree/ui_glue.vim
 38: ~/.vim/pack/vendor/start/nerdtree/nerdtree_plugin/exec_menuitem.vim
 39: ~/.vim/pack/vendor/start/nerdtree/nerdtree_plugin/fs_menu.vim
 40: ~/.vim/pack/vendor/start/nerdtree/nerdtree_plugin/vcs.vim
 41: ~/.vim/pack/vendor/start/tabular/plugin/Tabular.vim
 42: ~/.vim/pack/vendor/start/tabular/after/plugin/TabularMaps.vim
 43: ~/.vim/pack/vendor/start/tabular/autoload/tabular.vim
 44: /usr/share/vim/vim81/scripts.vim
 45: ~/.vim/pack/plugins/start/vim-terraform/syntax/terraform.vim
 46: ~/.vim/pack/plugins/start/lightline/autoload/lightline.vim
 47: ~/.vim/pack/plugins/start/lightline/autoload/lightline/tab.vim
 48: ~/.vim/pack/plugins/start/lightline/autoload/lightline/colorscheme/default.vim
 49: ~/.vim/pack/plugins/start/lightline/autoload/lightline/colorscheme/powerline.vim
 50: ~/.vim/pack/plugins/start/lightline/autoload/lightline/colorscheme.vim
```

**Comment by dimbleby** [comment]
The `ftplugin` file is not being loaded.  What does `:filetype` say?  I expect `help :filetype` will put you on the right track.

You'll also need `terraform` to be in your path.

**Comment by Chris-Leeworthy** [comment]
`:filetype` says `filetype detection: ON  plugin:OFF. indent: OFF` is that right or wrong?  I can change the values temporarily with `:filetype plugin on` but as soon as I leave vim and go back in it resets back, can I set them in .vimrc somehow?  Changing interactively options doesn't seem to make the commands work.

I can run terraform from the command line so I assume it is in my path
```
which terraform
/usr/local/bin/terraform
```

**Comment by dimbleby** [comment]
It doesn't look as though you "missed" some of the output previously, it looks as though you've changed something and are now seeing different results.

Do you have it working now?  If and when you do, please do report back - perhaps the next person who has the same problem can benefit.

**Comment by Chris-Leeworthy** [comment]
Nothing changed.  I could not get it to work.
In the end I used Homebrew to install vim 8.2 and everything works fine.  I still can't get it to work with the MacOS default vim (8.1)

**Comment by thizzle** [comment]
I don't know enough about how vim, but I ran `vim -V9logfile.log` to write detailed log output to a file. In that file, I found this snippet:

```
chdir(/usr/share/vim/vim82/indent)
fchdir() to previous dir
line 14: sourcing "/usr/share/vim/vim82/indent/tf.vim"
finished sourcing /usr/share/vim/vim82/indent/tf.vim
continuing in <SNR>8_LoadIndent
Executing FileType Autocommands for "*"
autocommand call s:LoadFTPlugin()

not found in 'runtimepath': "ftplugin/tf.vim ftplugin/tf_*.vim ftplugin/tf/*.vim"
Executing BufRead Autocommands for "*"
autocommand if !did_filetype() && expand("<amatch>") !~ g:ft_ignore_pat | runtime! scripts.vim | endif
```

It looks like vim was trying to load `ftplugin/tf.vim` or similar paths, but could not find it. When I looked at the code layout for this plugin, I found `ftplugin/terraform.vim` but not `ftplugin/tf.vim`. I renamed this file to `ftplugin/tf.vim` as vim seems to be looking for it there, and that worked. This plugin works for me now, so that was my workaround.

Thanks for your hard work on this plugin!
