### ISSUE TITLE
feature request: identify markdown embedded in comments (for syntax highlighting)

### ISSUE THREAD

**Issue by ketzacoatl** [hashivim/vim-terraform#15]
When using https://github.com/segmentio/terraform-docs, you have the option of embedding docs for your modules in a comment block. See https://github.com/segmentio/terraform-docs/blob/master/_example/main.tf for an example. If you write those embedded docs in markdown, they're still in a block comment, so you don't get any markdown syntax highlighting (as comments, they're all-blue).

I have zero experience with syntax highlighting in vim plugins, so I'm not sure how difficult this would be, but I think the feature would be really useful, and I would be happy to help make this happen in any way that I can.

One other note: it might be possible to simplify this by relying on the `/**` that terraform-docs uses to identify the block comment as an embedded doc (`/*` will be ignored, so `/**` could be used to identify this type of block, with the ` *` starting each line highlighted in blue and with the rest of the line getting markdown syntax highlighting).

**Comment by pgporada** [comment]
Oh my gosh, that's actually a really awesome plugin. I should have looked at this a long time ago.

**Comment by tagirb** [comment]
@ketzacoatl see here: http://vim.wikia.com/wiki/Different_syntax_highlighting_within_regions_of_a_file

**Comment by dimbleby** [comment]
Probably time to admit that this isn't going to happen, though if anyone is motivated enough to start putting together a pull request I expect we'd be interested.
