### ISSUE TITLE
Allow hot-swapping of g:terraform_align

### ISSUE THREAD

**Issue by LoicAG** [hashivim/vim-terraform#153]
In most cases, the `=`-alignment feature is extremy useful and welcome; but in some cases, I'd like to be able to disable it.

I've added the following to my `.vimrc`:
```
" Toggle vim-terraform alignment with F3
" TODO fix: variable is toggled, but plugin always aligns
nnoremap <F3> :call ToggleTerraformAlign()<CR>
function! ToggleTerraformAlign()
  if get(g:, 'terraform_align', 0)
    let g:terraform_align = 0
  else
    let g:terraform_align = 1
  endif
  echo g:terraform_align
endfunction
```

This does toggle the variable, but the actual alignment function doesn't take it in consideration; would it be possible to change the code to allow for the alignment to be enabled/disabled on-demand, without having to reload the plugin or to restart vim ?

**Comment by dimbleby** [comment]
The variable is used to decide whether or not to set [this mapping](https://github.com/hashivim/vim-terraform/blob/ffdf2dc17aaef733164a7079f95dd74f6cda9241/ftplugin/terraform.vim#L34) when a terraform file is loaded.

If you want to toggle alignment, you can toggle this mapping on and off.

Hope that helps.

**Comment by LoicAG** [comment]
That does help, thanks!

**Comment by LoicAG** [comment]
FYI this is what my `.vimrc` now looks like:
```
" Toggle vim-terraform alignment with F3
nnoremap <F3> :call ToggleTerraformAlign()<CR>
function! ToggleTerraformAlign()
  if get(g:, 'terraform_align', 0)
    let g:terraform_align = 0 " Doesn't do anything except memorize the state
    iunmap <buffer> <silent> =
    echo "Terraform align disabled"
  else
    let g:terraform_align = 1 " Doesn't do anything except memorize the state
    inoremap <buffer> <silent> = =<Esc>:call terraform#align()<CR>a
    echo "Terraform align enabled"
  endif
endfunction
```

**Comment by yermulnik** [comment]
@LoicGombeaud Thanks for the great solution! 👍🏻
