### ISSUE TITLE
Format on save not working

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [hashivim/vim-terraform#159]
I have set in my `~/.vimrc`

```
let g:terraform_fmt_on_save=1
```

However when saving, the text is not formatted.

However the `:TerraformFmt` seems to be working when running it manually.

**Comment by dimbleby** [comment]
Works fine here.  The autcommand is set up [here](https://github.com/hashivim/vim-terraform/blob/aa7877acb5dd81bed70c1188667b76cfde5b67bf/ftplugin/terraform.vim#L58-L64), hard to see how `:TerraformFmt` could be working but that not.

Maybe you have something else in your `.vimrc` that somehow breaks this?!?  Do update us if you figure it out, perhaps the next person will appreciate it.

**Comment by pantelis-karamolegkos** [comment]
Closing this as it seems to be working fine! Apologies for the hassle
