### ISSUE TITLE
Add ability to autoformat hcl files on save

### ISSUE THREAD

**Issue by jmreicha** [hashivim/vim-terraform#165]
It would be nice to have have the ability to automatically format hcl files as part of the `g:terraform_fmt_on_save = 1` functionality. Right now I have some extra configuration in my vimrc file but was surprised at how long it took to figure out as I somewhat expected the format these file on save.

Here's the extra config if anyone finds it useful.

```
autocmd BufWritePre *.hcl call terraform#fmt()
```

**Comment by dimbleby** [comment]
https://github.com/hashivim/vim-terraform#use-with-other-hcl-files

which is to say that I'm not in general looking to expand this plugin to be more widely scoped than terraform.  But would accept an MR noting the above in that section of the README.

**Comment by jmreicha** [comment]
Got it, thanks. I'll throw something in there!
