### ISSUE TITLE
Error detected while proccesing  function <SNR>214_VimCloseCallBack[11]..<SNR>214_VimExitCallBack[22]

### ISSUE THREAD

**Issue by madipietro** [hashivim/vim-terraform#172]
Hello folks, I'm having an annoying error when editing terraform files with Vim using the plugin. 

I installed the plugin using vimbunble.

Vim version:
```
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 16 2022 12:09:56)
Included patches: 1-4106
Compiled by Arch Linux
```

My config calling the plugin:

```
"terraform
Plugin 'hashivim/vim-terraform'
"end terraform
```

The error if I start vim in verbose mode and I open a TF file:

```
Error detected while processing function <SNR>214_VimCloseCallback[11]..<SNR>214_VimExitCallback[22]..function <SNR>214_VimCloseCallback[11]..<SNR>214_VimExitCallback[15]..<lambda>8[1]..<SNR>212_ExitCallback[28]..<SNR>211_HandleExit[24]..ale_linters#terraform#terraform#Handle:
line   17:
E716: Key not present in Dictionary: "detail"
E116: Invalid arguments for function add
Error detected while processing function <SNR>214_VimCloseCallback:
line   11:
E171: Missing :endif
```

If I just comment the calling of the plugin on my ```.vimrc``` the error disappears so I think the error is related to the plugin. Also I installed the plugin again today but without a good result. 

Thanks a lot!.

**Comment by dimbleby** [comment]
> ale_linters#terraform#terraform#Handle

try ALE?

**Comment by madipietro** [comment]
> > ale_linters#terraform#terraform#Handle
> 
> try ALE?

Hi @dimbleby I  tried installing ale plugin ( it wasn't installed ), but same error here :( Why do I need Ale ? is possible to use this plugin just with tflint ?

**Comment by madipietro** [comment]
> my point is that you call stack clearly shows that the error is happening in function coming from ALE. Make sure you have the latest version of that plugin, search their issue tracker, ask for help over there.

Ah oks! thanks!
