### ISSUE TITLE
terraform_fmt_on_save not working with in after/ftplugin/terraform.vim

### ISSUE THREAD

**Issue by FilBot3** [hashivim/vim-terraform#175]
So, I can put a `terraform.vim` file in to:

- `~/.config/nvim/ftplugin/terraform.vim`

with the contents of:

```vim
let g:terraform_fmt_on_save=1
```

This works, but when I put it into:

- `~/.config/nvim/after/ftplugin/terraform.vim`

I see the script is loaded, but the format on save doesn't seem to work. Any ideas why?

**Comment by dimbleby** [comment]
no (and it works for me)

do report back if you figure it out, perhaps the next person will benefit
