### ISSUE TITLE
.tf filetype detection seems broken in more recent Vim/NeoVim versions?

### ISSUE THREAD

**Issue by smheidrich** [hashivim/vim-terraform#179]
I'm running NeoVim 0.7.2 with this plugin installed via vim-plug, but when I open a `.tf` file, the filetype is just empty. It works fine for `.hcl` files.

Curiously, if I comment out [this line](https://github.com/hashivim/vim-terraform/blob/d00503de9bed3a1da7206090cb148c6a1acce870/ftdetect/hcl.vim#L3) where you disable Vim's native `.ft` filetype detection, it works. But that seems to be because recent versions of Vim [are able to recognize `.tf` files as Terraform](https://github.com/vim/vim/blob/be19d78c3d44221cbc38fbb5bac19302345c1def/runtime/autoload/dist/ft.vim#L1060), so with this line removed, Vim's native detection kicks in and sets the filetype:

```
:autocmd filetypedetect BufRead,BufNewFile *.tf
--- Autocommands ---
filetypedetect  BufReadPost
    *.tf      call dist#ft#FTtf()
```

So that can't be the underlying issue (although it would probably make sense to have a condition there to let Vim handle this for recent versions, because then users who want to be able to detect both file types denoted by `.tf` can do so).

Based on Vim's own autocmd being in group `filetypedetect`, I tried adding `filetypedetect` as the group for the [four autocmds](https://github.com/hashivim/vim-terraform/blob/d00503de9bed3a1da7206090cb148c6a1acce870/ftdetect/hcl.vim#L4-L7) setup by vim-terraform, and that made it detect the filetype correctly as well. But there is probably a reason why you don't have `filetypedetect` as the group there, so let me know what you think.

**Comment by dimbleby** [comment]
filetype detection is executed from https://github.com/vim/vim/blob/be19d78c3d44221cbc38fbb5bac19302345c1def/runtime/filetype.vim#L2745, which is already inside a group: it is correct not to add another group in our own file.

#133 was a bit similar, the reporter in that was using a plugin manager that messed with the runtime path and not following the associated instructions correctly.

Perhaps you're doing something similar?

**Comment by smheidrich** [comment]
I see, thanks for the explanation and the links!

I haven't figured out exactly what's causing this yet but as you explained this plugin is doing everything correctly, so I'll close the ticket.

**Comment by smheidrich** [comment]
All right, for anyone who has the same issue in the future, the source of the bug in my case was another plugin's ([vimoutliner](https://github.com/vimoutliner/vimoutliner)) `ftdetect` script leaving the `augroup filetypedetect` script at the end of its execution. I've opened an issue with them here: https://github.com/vimoutliner/vimoutliner/issues/185

I'm sure this is not the only plugin that does this, so again for anyone who has the same issue, it probably makes sense to go into your Vim plugin folder and run `rg 'augroup' $(find . -path '*/ftdetect/*.vim')` to see if you have any `ftdetect` scripts that (wrongly) close the augroup.

What pointed me towards this being a potential cause was [this comment](https://github.com/vim/vim/blob/6a7c7749204b256e779c245b1e999bf852ad7b64/runtime/filetype.vim#L2747-L2750) in Vim's `filetype.vim`, where it is noted that any of the `ftdetect` scripts it ran could have ended the augroup context.
