### ISSUE TITLE
Add tenv / opentofu support

### ISSUE THREAD

**Issue by kvendingoldo** [hashivim/vim-terraform#191]

**Comment by dimbleby** [comment]
Unclear what you are asking for.  

A merge request would be the most explicit way to set out what you want to see.

**Comment by nburns** [comment]
all that's required is a config change, I added the following to my vimrc, after installing opentofu, and reading the docs here: https://github.com/hashivim/vim-terraform/blob/24de93afb05078bac6a2e966402cc1f672277708/doc/terraform.txt#L27

```vim
let g:terraform_binary_path="tofu"
```
