### ISSUE TITLE
tfvars is not hcl filetype

### ISSUE THREAD

**Issue by mattn** [hashivim/vim-terraform#196]
If terraform.tfvars is below

```
xxx="yyy"
```

terraform-lsp handle it has errors.

```
terraform.tfvars|1 col 1 error| Terraform:Error:Unexpected attribute: An attribute named "xxx" is not expected here
```

**Comment by dimbleby** [comment]
Does not reproduce for me: but anyway it sounds as though you should report this to terraform-lsp and not here
