### ISSUE TITLE
Commenting multiple lines with tcomment uses multiple /* */

### ISSUE THREAD

**Issue by jleclanche** [hashivim/vim-terraform#20]
If I select multiple lines and hit `cc`, I will end up with each line wrapped in a `/* */`.

It should either use a single `/* */` for the whole block or use `//` for every line.

I'm not sure if the fault lies with tcomment or vim-terraform. I suspect the latter.

**Comment by pgporada** [comment]
I was able to do the following with success.

1.  visually select a block of terraform resources
1. press `ctrl shift _` and press `b` directly after

The results turned
```
 resource "aws_route53_record" "bastion-pub" {
   zone_id = "${var.public_zone_id}"
   name    = "bastion.${var.public_domain}"
   type    = "A"
   ttl     = "60"
   records = ["${aws_instance.bastion.public_ip}"]
 }
```
into
```
/*
 resource "aws_route53_record" "bastion-pub" {
   zone_id = "${var.public_zone_id}"
   name    = "bastion.${var.public_domain}"
   type    = "A"
   ttl     = "60"
   records = ["${aws_instance.bastion.public_ip}"]
 }
 */
```

That's what you've been expecting to have happen, correct?

**Comment by tmichel** [comment]
I think tcomment defaults to line-wise comments but the `commentstring` is not set up for terraform files. 

As a quick workaround I have this in my .vimrc file:

```viml
autocmd FileType terraform setlocal commentstring=#\ %s
```

This will do a line-wise comment but use `#` character instead of `/* */`.

**Comment by pgporada** [comment]
@tmichel Thanks for the tip, I'll see what I can do about fixing that for this repo.

**Comment by dimbleby** [comment]
Default commentstring is `#%s` since #65, so can close this now?
