### ISSUE TITLE
Better highlighting for variables

### ISSUE THREAD

**Issue by neilhwatson** [hashivim/vim-terraform#28]
Consider this ss
![tf](https://cloud.githubusercontent.com/assets/1221339/24920245/88559d0a-1eb4-11e7-9d57-ecdd6ee144c4.png)

There should be some extra highlighting between the map parts of the variables ${var.my["HERE"]}.

**Comment by pgporada** [comment]
Thanks for being patient @neilhwatson. Cheers to @ashb!
