### ISSUE TITLE
different name for augroup?

### ISSUE THREAD

**Issue by kevinburke** [hashivim/vim-terraform#29]
I defined the following settings in my `nvim/init.vim` file and was a little confused they weren't being applied.

```vim
    augroup terraform
        autocmd BufEnter *.tf set softtabstop=2
        autocmd BufEnter *.tf set tabstop=2
        autocmd BufEnter *.tf set shiftwidth=2

        autocmd FileType hcl,terraform autocmd BufWritePre <buffer> :call TerraformFormat()<CR>
        autocmd BufRead,BufNewFile *.tf setfiletype hcl
    augroup END
```

It took me a lot of time to figure out that there was already a `terraform` augroup defined.

Is there a way to warn about this conflict instead of silently ignoring my changes?

**Comment by pgporada** [comment]
@kevinburke 
I will figure out how to do this. It may take a while. I'm not the best at vimscript.
