### ISSUE TITLE
syntax highligting breaks when using ternary operator with strings

### ISSUE THREAD

**Issue by Telling** [hashivim/vim-terraform#34]
With this expression:

```hcl
  tags {
    Name              = "${var.environment == "staging" ? "sgn-stg-${var.application}" : "sgn-prd-${var.application}"}"
    "sgn:application" = "${var.application}"
    "sgn:environment" = "${var.environment}"
    "sgn:deployment"  = "${var.application}:${var.environment}"
  }

```

syntax highlighting seems to break for the rest of the document, and the highlighting itself looks weird:

<img width="886" alt="screen shot 2017-07-08 at 16 18 43" src="https://user-images.githubusercontent.com/741217/27986060-534975b6-63f9-11e7-95e4-91ca191e8c24.png">

**Comment by pgporada** [comment]
When I get back from my honeymoon I'll take a look. Speaking of that, I'm off!
