### ISSUE TITLE
Extract HCL into a separate plugin

### ISSUE THREAD

**Issue by markcornick** [hashivim/vim-terraform#4]
HCL will be used in Nomad as well as Terraform, so it's probably worthwhile to extract into a vim-hcl plugin, or to see if someone else has already done this.

**Comment by markcornick** [comment]
https://github.com/frntn/terraform-kickstart/blob/master/hcl.vim might be a useful starting point

**Comment by ketzacoatl** [comment]
https://github.com/b4b4r07/vim-hcl is another potential starting point.

**Comment by Mayeu** [comment]
Here is another possible starting point: https://github.com/jvirtanen/vim-hcl

**Comment by dimbleby** [comment]
Probably time to admit that this isn't going to happen, though if anyone is motivated enough to start putting together a pull request I expect we'd be interested.
