### ISSUE TITLE
Missing outdent if closing brace is at end of a non-empty line

### ISSUE THREAD

**Issue by ofavre** [hashivim/vim-terraform#52]
See the following code, indented using vim's `=` command:

```
resource "google_compute_instance" "foo" {
  name = "foo"
  scheduling {
    preemptible = "true"
    automatic_restart = "false" }
    boot_disk { initialize_params { image = "bar" } }
  }
```

The last two lines – `boot_disk` and the final `}` – have one extra indent level.

**Comment by pgporada** [comment]
You're expecting to see the following instead?
```
resource "google_compute_instance" "foo" {
  name = "foo"
  scheduling {
    preemptible = "true"
    automatic_restart = "false" }
  boot_disk { initialize_params { image = "bar" } }
}
```

**Comment by dimbleby** [comment]
So far as I can tell, the given example is not valid terraform - I get errors "An argument definition must end with a newline." (for the `automatic_restart` line) and "A single-line block definition can contain only a single argument..." (for the `boot_disk` line)

Suggest just closing this out, don't see any point putting effort into 'fixing' the indentation for bad syntax.
