### ISSUE TITLE
\ should be followed by /, ? or & line 1242

### ISSUE THREAD

**Issue by barthalion** [hashivim/vim-terraform#60]
After installation of hashivim/vim-terraform, Vim throws list of errors at startup:

```
E10: \ should be followed by /, ? or &
line 1243:
E10: \ should be followed by /, ? or &
line 1244:
E10: \ should be followed by /, ? or &
line 1245:
E10: \ should be followed by /, ? or &
line 1246:
E10: \ should be followed by /, ? or &
line 1247:
E10: \ should be followed by /, ? or &
line 1248:
E10: \ should be followed by /, ? or &
line 1249:
E10: \ should be followed by /, ? or &
```

It repeats up to number 1270, next occurences are 1281, 1283, 1287 and 1289.

hashivim/vim-terraform is at 76799270813db362b13a56f26cd34f668e9e17a4
vim 8.0.1542

Any ideas what's wrong?

**Comment by barthalion** [comment]
Slimmed down vimrc I can reproduce it with:

```
filetype plugin indent on
syntax enable

set omnifunc=syntaxcomplete#Complete
set background=dark
set number

call plug#begin('~/.vim/bundle/')
	Plug 'hashivim/vim-terraform'
call plug#end()
```

**Comment by pgporada** [comment]
I've updated the terraform vim syntax to support TF 0.11.5. I am unable to reproduce this using https://github.com/junegunn/vim-plug , your vimrc, and the latest vim-hashicorp.

**Comment by barthalion** [comment]
Somehow it goes away after enabling 20 plugins more, so guess it's something with my Vim version? What's the version of yours?

(EIther way, closing.)
