### ISSUE TITLE
heredoc multiline syntax highlighting doesn't work correctly when indented

### ISSUE THREAD

**Issue by Strayer** [hashivim/vim-terraform#62]
It seems that the heredoc multiline syntax highlighting doesn't parse correctly when indenting the closing phrase:

![broken syntax highlighting](https://user-images.githubusercontent.com/310624/38505347-3c15788a-3c17-11e8-930d-a6923ee87ccb.png)

![working syntax highlighting](https://user-images.githubusercontent.com/310624/38505522-a5b5bbc4-3c17-11e8-84bc-eab084123452.png)

The former is how we format our terraform scripts, frequently breaking the vim syntax highlighting :/ 

I guess changing `end=/^\z1/` to something like `end=/^\s*\z1/` [here](https://github.com/hashivim/vim-terraform/blob/master/syntax/terraform.vim#L1208) might fix this, but I don't have experience with VIM syntax highlighting, so this might break something.

```
locals {
  test = <<EOF
    something something
  EOF
}

locals {
  test = "123"
}
```

**Comment by rkennedy** [comment]
The current behavior matches [what's documented](https://www.terraform.io/docs/configuration/syntax.html):

> Multiline strings can use shell-style "here doc" syntax, with the string starting with a marker like `<<EOF` and then the string ending with `EOF` on a line of its own. The lines of the string and the end marker must _not_ be indented.

However, it doesn't match what [the hcl library's scanner](https://github.com/hashicorp/hcl/blob/master/hcl/scanner/scanner.go#L393) actually reads. The scanner accepts any amount of indentation for the heredoc anchor. (The scanner also allows the anchor to include digits and lowercase letters, and it allows the anchor to start with a hyphen to indicate that the _contents_ of the heredoc string are indented.)
