### ISSUE TITLE
vim-terraform doesnt follow sym links instead it creates new file when edited

### ISSUE THREAD

**Issue by ivan85viv** [hashivim/vim-terraform#64]
I have a sym link which when I decide to edit it doesn't edit the original file but instead it creates a new file. This happens with latest vim-terraform. 

=== reproducing ===
cat > variables.tf 
variable "var1" {
  default = "example"
}
mkdir test && cd test
ln -s ../variables.tf variables.tf

And then if cd to test and I edit variables.tf it destroys the sym link and create a file variables.tf

**Comment by lsc** [comment]
This sounds like a vim configuration issue, not a vim-terraform specific one.

Have you tried to reproduce this without vim-terraform loaded ?

**Comment by ivan85viv** [comment]
yeah thats how I found its vim-terraform issue

**Comment by sedlund** [comment]
@ivan85viv I cannot reproduce - my system works fine.

**Comment by pgporada** [comment]
I'm curious if @ivan85viv has or had set `set g:terraform_fmt_on_save=1` because that function will run `terraform fmt -write ${TEMPFILE}` which may be the cause of the symlink destruction. I'm investigating.

**Comment by ivan85viv** [comment]
thanks for commenting ... no I do not have it set ... the only thing I set is `let g:terraform_align=1` For the record this is my vimrc
```
" osx/mac and backspace movements enabling
set backspace=indent,eol,start

" remember history
set history=1000

execute pathogen#infect()
filetype plugin indent on

colorscheme delek

"# basic options
syntax on
set laststatus=2
" Enable display of matching open/close
set showmatch
set showmode

" Set the terminal title when editing
set title

" " Enable auto-indenting
set autoindent
"filetype plugin indent on

" Turn tabs into spaces
"set expandtab



" Search settings
set hlsearch " Highlight results
set ignorecase " Ignore casing of searches
set incsearch " Start showing results as you type
set smartcase " Be smart about case sensitivity when searching

" Backup settings
set backupdir=~/.vim/backups
set directory=~/.vim/swaps
set undodir=~/.vim/undo

" Plugin Settings
let g:terraform_align=1
```

I just did the same steps you did and I can see that the sym link is destroyed and it becomes a file under the test dir.

**Comment by pgporada** [comment]
What OS are you using?

**Comment by pgporada** [comment]
Let me know if I need to re-open this issue.

**Comment by ivan85viv** [comment]
Somehow I missed this - its High Sierra (10.13)

**Comment by diegombeltran** [comment]
I think I have the same problem:

If I edit a .tf when changing dir to a symlinked path, TerraformFmt doesn't work:
![imagen](https://user-images.githubusercontent.com/7081281/62298822-07b4b480-b474-11e9-8882-0db060087845.png)

If I edit the same file in the same location but without entering the symlinked path (By using absolute path or even the symlink but out of the path), it works.

**Comment by svanharmelen** [comment]
I'm having the exact same issue as described by @diegombeltran

**Comment by svanharmelen** [comment]
After playing around a bit, this turns out to be related to some logic[1][2] in Terraform that always tries to use relative paths in combination with how vim uses paths.

You can see the problem by running `:pwd` and `:echo system('pwd')`. Both commands will show different paths which is the root cause of this problem.

I think the easiest way to fix this is to make sure the `terraform` command is executed from the same directory by changing line 10:

```
- let output = system('terraform fmt -write ' . l:tmpfile)
+ let output = system('cd "' . resolve(expand('%:p:h')) . '" && terraform fmt -write ' . l:tmpfile)
```

Shall I make a PR for that @pgporada? Or do you prefer the solution @dimbleby suggested?

[1] https://github.com/hashicorp/terraform/blob/master/command/fmt.go#L125
[2] https://github.com/hashicorp/terraform/blob/master/command/meta_config.go#L25
