### ISSUE TITLE
Is it possible to fold all sections at start time?

### ISSUE THREAD

**Issue by roman8422** [hashivim/vim-terraform#68]
Vim starts with all sections unfolded for some reason.
I put 
```
let g:terraform_remap_spacebar=1
```
and
```
let g:terraform_fold_sections=1
```
in .vimrc and folding works as expected by space key.
If it is by design, is there a way to make vim fold all sections at the start? Or maybe fold/unfold them all with some command.

**Comment by pgporada** [comment]
You would like to have an auto-fold and auto-unfold key?

**Comment by roman8422** [comment]
@pgporada more like "fold all" and "unfold all" keys.

**Comment by padde** [comment]
@roman8422 Vim has some useful builtin commands to work with folds, I recommend you check those out

* `zi` to toggle folding (effectively opens all folds/restores previous folding)
* `za` to toggle a single fold (contratry to the tf-specific mapping, this will work with all file types)
* `zx` to open fold under cursor and close all other folds

To learn more, take a look at `:h fold-commands`.

If you want to close all folds on startup, you can add the following line to your `~/.vimrc`:

    au FileType terraform setlocal foldlevel=0

**Comment by roman8422** [comment]
Thank you @padde! It's exactly what I was looking for.
