### ISSUE TITLE
:TerraformFmt not valid editor command

### ISSUE THREAD

**Issue by tr0njavolta** [hashivim/vim-terraform#77]
Noticed that the ":TerraformFmt" command no longer works in Vim, so it seems that the plugin has changed or isn't loading properly, or something.
![image](https://user-images.githubusercontent.com/8883519/50992242-91a32d00-14e4-11e9-8ca6-a95263adfc7a.png)

**Comment by tr0njavolta** [comment]
ignore - reinstalled with no issue.

**Comment by pgporada** [comment]
Hooray!
