### ISSUE TITLE
kubernetes_role_binding not working

### ISSUE THREAD

**Issue by mkozjak** [hashivim/vim-terraform#81]
<img width="355" alt="screenshot 2019-02-16 at 04 59 15" src="https://user-images.githubusercontent.com/3506172/52894325-c4a5a400-31a7-11e9-85fc-e3719734ecdd.png">

Latest versions of everything.

**Comment by pgporada** [comment]
Thanks! I'll run a provider update tomorrow as soon as I get a chance to
sit down at the computer.

**Comment by pgporada** [comment]
Fixed by latest commit!
