### ISSUE TITLE
Why are the majority of ftplugins defined in after/ftplugin

### ISSUE THREAD

**Issue by dsifford** [hashivim/vim-terraform#86]
Is there a reason that the majority of ftplugins are in after/ftplugin? 

Also, and possibly more importantly, may I suggest the avoidance of using `set` (rather than `setlocal`) when defining options, and also defining a `b:undo_ftplugin`?

ping: @vancluever

https://github.com/hashivim/vim-terraform/blob/c818b6410a6894e7c765cc9eba64f3dcefa2f6ed/ftplugin/terraform.vim#L4

Thanks for considering.

**Comment by vancluever** [comment]
@dsifford I honestly don't have the answer to these questions. I didn't write the plugin as a whole and #80 was merged without mentioning that it might be better as a `setlocal` (which I'm not disputing for sure).

I don't have to time to change it right now, but I'm sure any contribution to improve the plugin would be appreciated.

**Comment by dsifford** [comment]
Sure thing. No worries, just wanted to make sure there wasn't some reason for this prior to opening a PR.

**Comment by dimbleby** [comment]
#89 addresses the above.
