### ISSUE TITLE
Remove various options, maybe?

### ISSUE THREAD

**Issue by dimbleby** [hashivim/vim-terraform#94]
I'm not sure that we'll want to do anything with this - it is, after all, possible that there are people using the features that I'm talking about.  But: I reckon that this plugin would be improved by removing various features that are either unneeded complication or out-of-scope.

- `g:terraform_commentstring` seems like an unnecessary piece of configuration
  - we should always just set it to the correct value, which is the default of `#%s`
  - if people really want to override for some reason, they can always do so in `~/.vim/after/ftplugin/terraform.vim`

- the function provided by `g:terraform_remap_spacebar` is in my opinion out of scope for this plugin - it's nothing to do with terraform at all, it's just setting up some mappings for folding
  - people who want to set up such mappings can do so themselves without our help
  - (I'm not even sure that it's a good mapping: I, and many others, use space as the leader key)

- `g:terraform_align` is interesting, but
  - it's broken, per #57, which I have no idea how to fix
  - given the existence of `terraform fmt` (and this plugin's wrapping of that), it's not tremendously useful - there's a very sane workflow that goes: type without `g:terraform_align`, and format when done (optionally on save).

- I'd be content to lose `g:terraform_fold_sections` and the `foldexpr` in favour of the simpler syntax-based folding per #91 

You might reasonably think that I could just not turn those things on, which is true, and which is what I do.

Still, they're all backed by code which is some sort of maintenance burden.  

So I thought I'd raise an issue to canvas opinion, at least.

Obviously this isn't all-or-nothing; it could be sensible to decide to drop some of those but not others.

**Comment by dimbleby** [comment]
Also even the `Terraform` command isn't that useful - per https://github.com/hashivim/vim-terraform/issues/98#issuecomment-514198832, all it really offers over `!terraform` is autocompletion of the first argument.  And even that, only if the version of your terraform binary matches the version that was used to build the plugin.

So I reckon I'd be happy to lose that too...

**Comment by kpankonen** [comment]
I personally appreciate `g:terraform_align` and would be sad to see it go (even with the ternary operator issue.)  Having things align as I'm typing is a nicer workflow for me than having to repeatedly save.

**Comment by dimbleby** [comment]
I've just merged three of the four proposed changes.  

We have a vote to keep `g:terraform_align`, and #105 seems to offer hope that it's fixable too - so let's keep that.

On reflection it's probably a bit too aggressive to remove the `Terraform` command.

So I'm going to call this done.
