### ISSUE TITLE
sed: 1: "s/Terraform//gI

### ISSUE THREAD

**Issue by revenue-hack** [hashivim/vim-terraform#95]
```
./update_automagic.sh 0.12.3
```

result: 
``` 
sed: 1: "s/Terraform//gI
": bad flag in substitute command: 'I'
-) You are trying to update this script for terraform 0.12.3 while you have
   terraform  installed at /usr/local/bin/terraform.
   Please update your local terraform before using this script.
```

env: 
```
OS: macOS Mojave(10.14.4)
```

bug?

**Comment by dimbleby** [comment]
I'm guessing that the intention was a lower-case `i` as some sort of future-proofing precaution against the output becoming `terraform V0.1.12`, maybe.  But let's see whether @pgporada can tell us what he'd had in mind.

(I'd probably have just gone `terraform version | head -n1 | sed 's/Terraform v//'`, and change it if they ever break it...)

**Comment by dimbleby** [comment]
No, wait, capital `I` is for case-insensitive, isn't it?  I mean it still looks over-complicated to me: but I don't see why it wouldn't work as it is.

**Comment by pgporada** [comment]
My system of choice has always been a linux kernel for this type of work. If you use GNU sed, unlike the version installed on an OSX device, it will work.

 ```
[phil@laptappy ~]
$ echo "PphHiIlL" | sed 's/p/x/gI'
xxhHiIlL
[phil@laptappy ~]
$ echo "PphHiIlL" | sed 's/p/x/g'
PxhHiIlL
```

**Comment by pgporada** [comment]
@revenue-hack I will run the provider and resource updates now.
